# Generated by Django 5.0.7 on 2024-07-27 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField()),
                ('informacion', models.TextField()),
                ('identificador_examen', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_laboratorio', models.IntegerField()),
                ('id_medicamento', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigos', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('arancel', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ciudad'],
                'unique_together': {('calle', 'numero', 'ciudad')},
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_antecedente_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.antecedentemedico')),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='antecedentemedico',
            name='id_patologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patologia'),
        ),
        migrations.CreateModel(
            name='PersonalMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidad')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Financiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('id_personal_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalmedico')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('id_personal_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalmedico')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='auth.group')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('id_patologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patologia')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entidad')),
                ('id_financiador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.financiador')),
                ('id_historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.historiaclinica')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_patologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patologia')),
                ('id_personal_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalmedico')),
                ('id_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipodocumento')),
                ('id_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('id_farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmacia')),
                ('id_patologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patologia')),
                ('id_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_turno', models.DateTimeField()),
                ('fin_turno', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalmedico')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('nro_documento', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('sexo', models.CharField(max_length=10)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('numero_telefono_2', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('factor_sanguineo', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='core.direccion')),
                ('id_informacion_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
                'unique_together': {('nombres', 'apellidos', 'nro_documento')},
            },
        ),
        migrations.AddIndex(
            model_name='antecedentemedico',
            index=models.Index(fields=['fecha_atencion'], name='fecha_atencion'),
        ),
    ]
