# Generated by Django 5.0.6 on 2024-07-09 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entidad",
            fields=[
                ("idEntidades", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                ("idEspecialidad", models.AutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FactorSanguineo",
            fields=[
                ("idFactor", models.AutoField(primary_key=True, serialize=False)),
                ("factor_sanguineo", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Financiero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idPrepagas", models.IntegerField()),
                ("descripcion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Laboratorio",
            fields=[
                ("idLaboratorio", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "idTipoDocumento",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Farmacia",
            fields=[
                ("idFarmacia", models.AutoField(primary_key=True, serialize=False)),
                ("medicamento", models.IntegerField()),
                (
                    "laboratorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.laboratorio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                ("idMedicamento", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "farmacia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicamentos",
                        to="core.farmacia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                ("idPaciente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=15)),
                ("apellido", models.CharField(max_length=15)),
                ("nro_documento", models.IntegerField()),
                ("fecha_nacimiento", models.DateField()),
                ("sexo", models.IntegerField()),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.entidad"
                    ),
                ),
                (
                    "factor_sanguineo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.factorsanguineo",
                    ),
                ),
                (
                    "prepaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.financiero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patologia",
            fields=[
                ("idPatologias", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "especialidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.especialidad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PacientePatologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
                (
                    "patologia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.patologia"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paciente",
            name="patologias",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.patologia"
            ),
        ),
        migrations.CreateModel(
            name="PatologiaMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.medicamento",
                    ),
                ),
                (
                    "patologia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.patologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalMedico",
            fields=[
                (
                    "idPersonalMedico",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "especialidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.especialidad",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paciente",
            name="personal_medico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.personalmedico"
            ),
        ),
        migrations.AddField(
            model_name="financiero",
            name="personal_medico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.personalmedico"
            ),
        ),
        migrations.CreateModel(
            name="PersonalMedicoEspecialidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.especialidad",
                    ),
                ),
                (
                    "personal_medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.personalmedico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalMedicoPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
                (
                    "personal_medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.personalmedico",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paciente",
            name="tipo_documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tipodocumento"
            ),
        ),
        migrations.CreateModel(
            name="Tratamiento",
            fields=[
                ("idTratamiento", models.AutoField(primary_key=True, serialize=False)),
                (
                    "patologia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.patologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatologiaTratamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patologia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.patologia"
                    ),
                ),
                (
                    "tratamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tratamiento",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paciente",
            name="tratamientos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tratamiento"
            ),
        ),
        migrations.CreateModel(
            name="TratamientoPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
                (
                    "tratamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tratamiento",
                    ),
                ),
            ],
        ),
    ]
