# Generated by Django 5.0.7 on 2024-08-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatadherence',
            name='start_datetime',
            field=models.CharField(max_length=20),
        ),
    ]
