# Generated by Django 5.0.7 on 2024-08-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financer',
            name='medical_staff',
        ),
    ]
