# Generated by Django 5.0.7 on 2024-08-07 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipousuario',
            old_name='tipo',
            new_name='type_user',
        ),
    ]
