# Generated by Django 5.0.7 on 2024-08-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='dia_turno',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fin_turno',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='inicio_turno',
        ),
        migrations.AddField(
            model_name='especialidad',
            name='descripcion',
            field=models.CharField(default='Descripcion Preterminada', max_length=255),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_turno',
            field=models.CharField(default='01-01-2024', max_length=10),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_turno',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado')], default='disponible', max_length=20),
        ),
    ]
