# Generated by Django 5.0.7 on 2024-07-23 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_turno', models.DateTimeField()),
                ('fin_turno', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalmedico')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
    ]
