# Generated by Django 5.0.7 on 2024-08-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatadherence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
