# Generated by Django 5.0.7 on 2024-08-07 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_financer_medical_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.address'),
        ),
    ]
