# Generated by Django 5.0.7 on 2024-08-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_treatadherence_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_photo',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/dzllpjhiv/image/upload/v1723578955/download_qsmmfm.png', max_length=255, null=True),
        ),
    ]
