# Generated by Django 5.0.7 on 2024-08-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tipousuario_id_usuario_remove_user_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
