# Generated by Django 5.0.7 on 2024-08-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_availability_day_alter_medicalstaff_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='description',
        ),
        migrations.AddField(
            model_name='crosstransplant',
            name='HLA_donor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crosstransplant',
            name='HLA_patient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathology',
            name='nomenclature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.nomenclature'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treat_duration',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='treat_indications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treat_medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treat_medication', to='core.medication'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treat_name',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='treat_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TreatAdherence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.CharField(max_length=10)),
                ('treat_duration', models.CharField(max_length=5)),
                ('treat_frecuency', models.CharField(max_length=5)),
                ('treat_adherence', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.treatment')),
            ],
        ),
    ]
