# Generated by Django 5.0.7 on 2024-07-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fileupload'),
        ('core', '0002_turno'),
    ]

    operations = [
    ]
