# Generated by Django 5.0.7 on 2024-08-05 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_turno_paciente_turno_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id_historia_clinica',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_personal_medico',
        ),
        migrations.AddField(
            model_name='antecedentemedico',
            name='id_personal_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personalmedico'),
        ),
        migrations.AddField(
            model_name='antecedentemedico',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_medicos', to='core.paciente'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
    ]
