# Generated by Django 5.0.7 on 2024-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_turno_dia_turno_remove_turno_fin_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmedico',
            name='telefono_consulta',
            field=models.IntegerField(default='0303456'),
            preserve_default=False,
        ),
    ]
