# Generated by Django 5.0.7 on 2024-08-12 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_treatment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='emergency_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_attention', models.DateField()),
                ('medical_studies', models.TextField(blank=True, null=True)),
                ('attention_observations', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_staff', to='core.medicalstaff')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_histories', to='core.entity')),
                ('pathology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathology', to='core.pathology')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_histories', to='core.patient')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='core.treatment')),
            ],
        ),
    ]
