# Generated by Django 5.0.7 on 2024-08-02 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personalmedico_telefono_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalMedicoReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_personal_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.personalmedico')),
            ],
        ),
    ]
