# Generated by Django 5.0.7 on 2024-08-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalmedico',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
