# Generated by Django 5.0.7 on 2024-08-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_url_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason_for_visit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
