# Generated by Django 5.0.7 on 2024-08-06 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tipousuario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_types',
        ),
        migrations.AddField(
            model_name='user',
            name='user_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tipousuario'),
            preserve_default=False,
        ),
    ]
