# Generated by Django 5.0.7 on 2024-08-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_personalinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='financer',
            name='affiliate_code',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AddField(
            model_name='financer',
            name='plan',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='url_photo',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
