# Generated by Django 5.0.7 on 2024-08-06 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_user_types_user_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tipousuario'),
        ),
    ]
