# Generated by Django 5.0.7 on 2024-08-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_financer_affiliate_code_financer_plan_user_url_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financer',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financer',
            name='plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
