# Generated by Django 5.0.7 on 2024-08-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_personalmedicoreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmedico',
            name='photo',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
