# Generated by Django 5.0.7 on 2024-08-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment_reason_for_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
