# Generated by Django 5.0.7 on 2024-08-04 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_personalmedico_id_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='paciente',
        ),
        migrations.AddField(
            model_name='turno',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='dia',
            field=models.CharField(choices=[('lunes', 'lunes'), ('martes', 'martes'), ('miércoles', 'miércoles'), ('jueves', 'jueves'), ('viernes', 'viernes'), ('sabado', 'sabado'), ('domingo', 'domingo')], max_length=10),
        ),
    ]
