# Generated by Django 5.0.7 on 2024-08-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_financer_affiliate_code_alter_financer_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financer',
            name='affiliate_code',
        ),
        migrations.RemoveField(
            model_name='financer',
            name='plan',
        ),
        migrations.AddField(
            model_name='patient',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
